CREATE TABLE T_DB_AUTOUPDATE
(
  DB_AUTOUPDATE_IN_PK INTEGER      NOT NULL AUTO_INCREMENT,
  COMPONENT_TX        VARCHAR(255) NOT NULL,
  MODIFIED_DT         DATETIME     NOT NULL,
  VERSION_TX          VARCHAR(20)  NULL,
  CONSTRAINT CNPK_DB_AUTOUPDATE PRIMARY KEY (DB_AUTOUPDATE_IN_PK),
  INDEX IX_DB_AUTOUPDATE_COMPONENT (COMPONENT_TX)
)
  ENGINE = InnoDB;

CREATE TABLE T_DB_AUTOUPDATE_LOCK
(
  DB_AUTOUPDATE_LOCK_IN_PK INTEGER      NOT NULL AUTO_INCREMENT,
  PROCESS_TX               VARCHAR(255) NOT NULL,
  LEASE_UNTIL_DT           DATETIME     NOT NULL,
  UNLOCK_KEY_TX            VARCHAR(255) NOT NULL,
  CONSTRAINT T_DB_AUTOUPDATE_LOCK PRIMARY KEY (DB_AUTOUPDATE_LOCK_IN_PK),
  CONSTRAINT CNUN_DB_AUTOUPDATE_LOCK UNIQUE (PROCESS_TX)
)
  ENGINE = InnoDB;

INSERT INTO T_DB_AUTOUPDATE (COMPONENT_TX, MODIFIED_DT, VERSION_TX) VALUES ('lib_db_autoupdate', now(), '1.1');
INSERT INTO T_DB_AUTOUPDATE (COMPONENT_TX, MODIFIED_DT, VERSION_TX) VALUES ('testovaci', now(), '3.1');
