DELIMITER $$;

CREATE TRIGGER TR_DENY_SUBJECT_DELETION
BEFORE DELETE
ON T_FRAUS_SUBJECT
FOR EACH ROW
  BEGIN
    IF OLD.id is not null THEN
      SIGNAL SQLSTATE '50000'
      SET MESSAGE_TEXT = 'Row cannot be removed';;
    END IF;;
  END
$$;

DELIMITER ;;;