darwin_mysql_junit:
    image: mysql:5.6
    environment:
     - MYSQL_USER=test
     - MYSQL_PASSWORD=test
     - MYSQL_ROOT_PASSWORD=test
     - MYSQL_DATABASE=test
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes:
     - ./initdb/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
     - "127.5.0.3:3306:3306"
darwin_oracle_junit:
    image: wnameless/oracle-xe-11g
    environment:
      - ORACLE_ALLOW_REMOTE=true
    ports:
     - "127.5.0.3:1521:1521"