ALTER TABLE T_DB_AUTOUPDATE DROP CONSTRAINT CNPK_AUTOUPDATE_COMPONENT;

DROP TABLE T_DB_AUTOUPDATE_PATCH;

DROP CREATE INDEX CNIX_T_DB_AUTOUPDATE_PATCH;

DROP INDEX CNUN_UNIQUE_PATCH;

DROP SEQUENCE SQ_T_DB_AUTOUPDATE_PATCH;

DROP TABLE T_DB_AUTOUPDATE_SQL;

DROP INDEX CNIX_T_DB_AUTOUPDATE_SQL;

DROP SEQUENCE SQ_T_DB_AUTOUPDATE_SQL;

UPDATE T_DB_AUTOUPDATE SET VERSION_TX = '2.9' WHERE COMPONENT_TX = 'lib_db_autoupdate';